// Generated by CoffeeScript 1.10.0
(function() {
  var CountyData, callback, fs, path;

  fs = require('fs');

  path = 'est14_WA.txt';

  fs.readFile(path, callback = function(err, data) {
    if (err) {
      return console.log(err);
    } else {
      return console.log(data.toString().split("\n"));
    }
  });

  CountyData = (function() {
    function CountyData(childrenCount, childrenPercentage, medianIncome, countyName) {
      this.childrenCount = childrenCount;
      this.childrenPercentage = childrenPercentage;
      this.medianIncome = medianIncome;
      this.countyName = countyName;
    }

    return CountyData;

  })();

}).call(this);
